# Generated by Django 4.2.1 on 2023-05-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriesmodel',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='recipesmodel',
            options={'verbose_name_plural': 'Recipes'},
        ),
        migrations.AddField(
            model_name='recipesmodel',
            name='products',
            field=models.TextField(blank=True),
        ),
    ]
