# Generated by Django 4.2.1 on 2023-05-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_categoriesmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriesmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
