# Generated by Django 4.2.1 on 2023-06-02 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_categoriesmodel_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriesmodel',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='recipesmodel',
            options={'verbose_name': 'recipe', 'verbose_name_plural': 'recipes'},
        ),
        migrations.RenameField(
            model_name='categoriesmodel',
            old_name='description',
            new_name='descriptioncat',
        ),
        migrations.RenameField(
            model_name='categoriesmodel',
            old_name='name',
            new_name='namecat',
        ),
    ]
