# Generated by Django 4.2.1 on 2023-06-02 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_categoriesmodel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriesmodel',
            old_name='descriptioncat',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='categoriesmodel',
            old_name='namecat',
            new_name='name',
        ),
    ]
