# Generated by Django 4.2.1 on 2023-06-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_descriptioncat_categoriesmodel_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipesmodel',
            old_name='categories',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='categoriesmodel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='recipesmodel',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='recipesmodel',
            name='link_video',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
