# Generated by Django 4.2.1 on 2023-06-04 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipesmodel_avatar_userreciperelation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreciperelation',
            old_name='book',
            new_name='recipe',
        ),
    ]
