# Generated by Django 4.2.1 on 2023-06-04 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0008_rename_book_userreciperelation_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesmodel',
            name='readers',
            field=models.ManyToManyField(related_name='recipes', through='recipes.UserRecipeRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
